orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/tests/test_owgradientdescent.py

With this pull request we updated:
* Modified gradient color to match to class.
* Fixed save image functionality 
* Added some more information to the report.

Gradient descent small updates and fixes

---

orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/owkmeans.py
orangecontrib/educational/widgets/owpolynomialclassification.py
orangecontrib/educational/widgets/tests/test_owgradientdescent.py
orangecontrib/educational/widgets/tests/test_owkmeans.py

Refs: "WebView/WebEngine: don't permit exposing QWidgets" in https://github.com/biolab/orange3/pull/1799

JS widgets: don't bridge via QWidget but via thin QObject instead

---

orangecontrib/educational/widgets/owkmeans.py
orangecontrib/educational/widgets/tests/test_owkmeans.py

**Interactive k-Means** crashes when data with a column with all `nan` values is sent to the widget and an attribute which corresponds to that column is selected.
Checks for valid values and fills combos only with valid attributes. Error message is changed.

[FIX] Interactive k-Means: do not crash on nan column

---

orangecontrib/educational/widgets/owpolynomialclassification.py
orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py

Polynomial Classification widget accept any learner (also if not classification). 
For Linear regression (which is not regression) it raises a fitting failed error which is not informative to a user.
Widget changes that raise the No classifier error (with message to user)  when the Linear regression present.

Fix: Polynomial Classification raise error when no classifier present

---

orangecontrib/educational/widgets/icons/category.svg

Each time Orange starts this message appears in a console:
> couldn't create image from  "EC2EE3FB7160215B.jpg"
Some lines removed in `category.svg` file.

[FIX] Category Icon: remove some lines which causes warning message

---

orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/tests/test_owgradientdescent.py

Connect **File** and **Gradient Descent**. Click _Run_ and then remove data connection between these two widgets. Orange then crashes.
Stop running when there is no data anymore.

[FIX] Gradient Descent: do not crash when auto play runs

---

orangecontrib/educational/widgets/owgradientdescent.py

Connect **File** and **Gradient Descent**.  Click _Run_ button and then remove **Gradient Descent** widget. Then Orange crashes because a thread is still working and there is no widget anymore.
Solved by `try except`.

[FIX] Gradient Descent: handle thread if widget removed

---

orangecontrib/educational/widgets/owpolynomialclassification.py
orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py

Put **Polynomial Classification** on canvas. Click checkbox _Show contours_. The widget crashes.
Do not try to draw contours if there is no data.

[FIX] Polynomial Classification: do not draw contours if no data

---

orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/owpolynomialclassification.py
orangecontrib/educational/widgets/owpolynomialregression.py

Setting the number of decimals to 7 is no longer necessary: after https://github.com/biolab/orange3/pull/3574, values are printed with `%g` by default.

Remove setting the number of decimals in ContinuousVariable

---

orangecontrib/educational/widgets/owpolynomialclassification.py

Polynomial classification crashes if the variable for coloring has missing values. From Sentry:
```
ValueError:  cannot convert float NaN to integer
(1 additional frame(s) were not displayed)
...
Module "orangecontrib.educational.widgets.owpolynomialclassification", in set_data
self.apply()
Module "orangecontrib.educational.widgets.owpolynomialclassification", in apply
self.replot()
Module "orangecontrib.educational.widgets.owpolynomialclassification", in replot
for _class in range(len(sd.domain.metas[0].values))]
Module "orangecontrib.educational.widgets.owpolynomialclassification", in <listcomp>
for _class in range(len(sd.domain.metas[0].values))]
Module "orangecontrib.educational.widgets.owpolynomialclassification", in <listcomp>
if (int(p.metas[0]) == _class and
```
Conversion to …

Polynomial classification: Fix crash on missing values

---

orangecontrib/educational/widgets/owkmeans.py

Should one type 'kmeans' as a quick menu search query, the educational k-Means widget would not appear.
A 'kmeans' keyword was added to the widget.

owkmeans: Add 'kmeans' (without '-') keyword for quick menu search

---

.travis.yml
setup.py

For merging https://github.com/biolab/orange3-educational/pull/73 it would be great to have Orange version at least 3.21.0 - some new signals. 
Changing minimal Orange version to 3.21.0

Changing minimal Orange version to 3.21.0

---

doc/conf.py

source_parsers is deprecated in sphinx config
source_parsers is now removed. recommonmark is moved to extensions

Docs: removed deprecated source_parsers

---

.travis.yml
orangecontrib/educational/widgets/utils/logistic_regression.py
orangecontrib/educational/widgets/utils/tests/test_linear_regression.py
orangecontrib/educational/widgets/utils/tests/test_logistic_regression.py

Logistic regression is made to work on two classes only but test provided case with more classes
- test changed
- logistic regression error on more classes

LogisticRegression: limit to two class values only

---

orangecontrib/educational/widgets/ow1ka.py
orangecontrib/educational/widgets/tests/test_ow1ka.py

Enka still uses `time.clock` which was deprecated in Python 3.3 and is removed in Python 3.8.
Replace with perf_counter

Fix enka to not use time.clock anymore

---

orangecontrib/educational/widgets/owkmeans.py

OWKmeans had wrongly set `want_main_area` to false.
With this PR I am setting it to `True`. I also removed the separator in the controls area which adds unneeded space.

[FIX] KMeans: Fix wrongly set want_main_area and remove separator

---

orangecontrib/educational/widgets/owrandomdata.py
orangecontrib/educational/widgets/tests/test_owrandomdata.py

Fixes #97.
1. Combo value was changed when the down key was pressed, and the `currentTextChanged` triggers adding a variables. This has been resolved by setting the focus policy to none.
2. Output summary is added and tested.

Random data: Add output summary, fix adding variables on keydown on combo

---

orangecontrib/educational/widgets/owkmeans.py
orangecontrib/educational/widgets/tests/test_owkmeans.py
orangecontrib/educational/widgets/utils/kmeans.py
orangecontrib/educational/widgets/utils/tests/test_kmeans.py

K-means depends on highchart. We'd prefer it didn't.
Other improvements:
- animate membership reassignment
- use domain model and context settings
- remove centroids by clicking
- UX simplifications - primarily targeting the most common use, that is, with painted data:
- hide combos with variables when there are only two
- show attribute names on axes, except when they are named x and y
- hide axis when there are only two attributes, names x and y and from interaval [0, 1]
- remove redundant elements (number of clusters, animation speed)
- use Orange's palettes
- prevent user from having more clusters than data points, instead of showing an error
- simplify the underlying kmeans code

Interactive K-Means: Remove Highchart, other improvements

---

orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/tests/test_owgradientdescent.py
orangecontrib/educational/widgets/utils/gradient_descent.py
orangecontrib/educational/widgets/utils/tests/test_linear_regression.py
orangecontrib/educational/widgets/utils/tests/test_logistic_regression.py

Gradient Descent uses highcharts. We'd prefer it didn't.
I changed this one less than the other two (k-meand and polynomial classification).
- Replaced highcharts with pyqtgraph
- Simplified GUI (speed is fixed, attr y and target are hidden for regression, buttons are reorganized)
- Mouse cursor changes to crosshair and shows the cost at the hovered point (computed by learner, not from grid)
- Show when hovering over points on optimization path
- Contour lines are bold when hovered, cost is shown
- Widget uses domain context handler, models etc.

Gradient Descent: Remove highcharts, other minor improvements

---

orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/owpolynomialclassification.py
orangecontrib/educational/widgets/utils/gradient_grid.py

After the replacing HighCharts with PyQtGraph background gradients are not smooth. 
- This PR smooths gradients of Gradient Descent and Polynomial Classification widget
- Turns antialiasing on for Gradient descent contours to smoothen them

Interpolate gradient grid

---

orangecontrib/educational/widgets/__init__.py
setup.py

In https://github.com/biolab/orange3-educational/pull/109 we changed the documentation theme to shpinx rtd theme. It was found out that it does not support htmlhelp builder. 
Since with this theme, it is not required to build the documentation with htmlhelp I am changing the setting such that they are compatible with html builder. From now on we build documentation with `make html` instead of `make htmlhelp`

Documentation: enable building with html builder

---

orangecontrib/educational/tests/__init__.py
orangecontrib/educational/widgets/owkmeans.py
orangecontrib/educational/widgets/tests/test_owgradientdescent.py
orangecontrib/educational/widgets/tests/test_owkmeans.py
orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py
orangecontrib/educational/widgets/tests/test_owpolynomialregression.py
setup.py
tox.ini

Orange now locks tables (in tests), thus the tests (and code) need to be fixed or locking disabled; preferrably the former.
Requires Orange3.31 with support for table locking.
Tests are fixed.
The code for k-means contained an actual bug: the output table included an array, which was subsequently changed by the module used in the widget.

Fixes for table locking

---

orangecontrib/educational/widgets/owpolynomialclassification.py

- When fitting failed, hovering produced error because the helper returned `None` instead of `False`.
- When there where no instances in the last class, the widget failed because the number of bins returned by bincount to determine non-empty classes did not match the number of classes.

[FIX] Fix minor bugs in Polynomial Classification

---

orangecontrib/educational/widgets/owpolynomialregression.py
orangecontrib/educational/widgets/tests/test_owpolynomialregression.py
tox.ini

1. Fixes #135 
2. Additionally: Polynomial Regression does not work with other regression models since it uses PolynomialLearner which is not compatible with learners that implement fit_storage instead of fit.
3. The widget ignored preprocessors attached to the Learner on the input. 
Fixes intercept when linear regression at the input
I think that using a Polynomial Features preprocessor is a better solution than having a separate learner for it. In this PR I implement a preprocessor for polynomial features instead of PolynomialLearner.
To discuss:
Polynomial features produce the bias parameter (x^0) when a fit intercept is selected (and this one is part of input features). If the Linear regression is on the input, it trains its intercept. In the coefficients table, they are summed up, …

Polynomial Regression: fix intercept value in output

---

orangecontrib/educational/widgets/owpolynomialregression.py
orangecontrib/educational/widgets/tests/test_owpolynomialregression.py

Polynomial features can become huge due to the exponentiation of numbers. Huge numbers (and number differences) can cause model algorithms to be numerically unstable. For example, a higher degree of polynomial features should result in a better fit to the curve, but when numbers are high and linear regression weight becomes really small, it is not the case anymore (because of numeric instability):
It can be fixed with normalization, but as discussed with Tomaz, it is better just to warn since it is an educational add-on, and we do not want to do any values changing in the background (which would also affect the model weights).

[ENH] Polynomial regression - warn about huge values

---

orangecontrib/educational/widgets/owgradientdescent.py
orangecontrib/educational/widgets/owkmeans.py
orangecontrib/educational/widgets/owpiecharts.py
orangecontrib/educational/widgets/owpolynomialclassification.py
orangecontrib/educational/widgets/owpolynomialregression.py

We don't know which object types are passed to methods for reporting, saving charts and copying to clipboard.
- Added comments with one of the four types handled by `ImgFormat` (`pg.GraphicsItem`, `QGraphicsScene`, `QGraphicsView`, `QWidget`), and the actual derived type, if applicable.
- Fix `graph_name` for k-means.
- Polynomial classification and k-means passed the object to be plotted as an argument to `report_plot`. If `graph_name` is given, it's better to use if for `report_plot` to avoid ambiguity.

Annotate graph_name with graph's types

---

orangecontrib/educational/widgets/owrandomdata.py

Random data fail on PyQt6 because of wrong super call in leaveEvent
Call correct super

Random data - Fix editor event
