orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/utils/color_transform.py
That bug appeared on widows system.
=> [FIX] Fixed bug with color brightening 

orangecontrib/educational/widgets/__init__.py
I went for soft red. If you hate it, please close the PR. :smile:
=> Changed color for Educational add-on

orangecontrib/educational/widgets/__init__.py
Red was too strong it was changed to light yellow.
=> [WIP] Changed color for Educational add-on

orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/tests/test_owkmeans.py, orangecontrib/educational/widgets/utils/color_transform.py, orangecontrib/educational/widgets/utils/kmeans.py, orangecontrib/educational/widgets/utils/tests/test_color_transform.py, orangecontrib/educational/widgets/utils/tests/test_kmeans.py
In this PR unit test for k-means were updated to cover more code.
=> Updated unit test for kmeans

orangecontrib/educational/widgets/owpolynomialregression.py, orangecontrib/educational/widgets/tests/test_owpolynomialregression.py
With this pull request we:
* added info box that contains informations about:
* used regressor
* RMSE of the regressor
* added error bars in the chart
=> Added info box and error bars in the chart

orangecontrib/educational/widgets/__init__.py
Widget background changed from red to light orange.
=> [FIX] Widget background color changed.

orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/resources/draggable-points.js, orangecontrib/educational/widgets/tests/test_owkmeans.py, orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owpolynomialregression.py, orangecontrib/educational/widgets/utils/tests/test_linear_regression.py
=> Various minor widgets updates

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, orangecontrib/educational/widgets/owpolynomialregression.py
NaN values crash widget.
Filters out NaN values.
+ Issue template and Pull Request template
=> [FIX] Polynomial Regression: remove nans

orangecontrib/educational/widgets/owpolynomialregression.py
Widget crashes when no cont. variables.
=> [FIX] Polynomial Regression: no continuous variables

orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/owpolynomialregression.py, orangecontrib/educational/widgets/tests/test_owgradientdescent.py, orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owpolynomialregression.py
Several errors.
1) Disable tests which take too much time (Travis failed due to `TimeoutError`).
2) Upgrade to Inputs and Outputs and fix tests in all four widgets.
3) Upgrade to `class Warning`.
4) Upgrade to iteration over `domain.variables` and not `domain`.
3) Concatenate lists not tuple and lists in **Polynomial Classification**.
4) Fitting bug in **Polynomial Classification** handled.
=> [FIX] Polynomial Classification: many bugs

orangecontrib/educational/widgets/owpolynomialregression.py
Add class variable to the output data.
=> Add class var to output table

orangecontrib/educational/widgets/owpolynomialclassification.py
=> [FIX] Polynomial Classification: learners on input

orangecontrib/educational/widgets/owpolynomialregression.py, orangecontrib/educational/widgets/tests/test_owpolynomialregression.py
Send data fails when there are rows with `nan` values in attributes array.
Use mask and select only matching values from class array.
=> [FIX] Polynomial Regression: filter class table

orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/tests/test_owgradientdescent.py
Does not work on sparse.
Convert those two or three columns which are needed to dense.
=> [FIX] Gradient Descent: work on sparse

orangecontrib/educational/widgets/icons/polynomialclassification.svg
Some error in `svg` file. Application always writes some output in a console:
```console
Could not resolve property : gridpattern
```
=> [FIX] Polynomial Classification: error in svg

orangecontrib/educational/widgets/owkmeans.py
=> [FIX] Interactive k-Means: handle thread if widget removed

orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/tests/test_owgradientdescent.py
Some unitests fail on timeout by Travis and were disabled
Reenabling and fixing disabled unit-tests
=> [wip] Reenabling and fixing disabled unit-tests

orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owgradientdescent.py, orangecontrib/educational/widgets/tests/test_owkmeans.py, orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owpolynomialregression.py
Does not work on sparse.
Similar as #45 .
Also fix check for `None`.
=> [FIX] Polynomial Classification: work on sparse

orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py
Timeout error in unit-tests
Some tests shortened and split into more functions
=> Unitest fix and cleanup

orangecontrib/educational/widgets/ow1ka.py, orangecontrib/educational/widgets/owgooglesheets.py, orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/owpiecharts.py, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/owpolynomialregression.py
Widgets in the addon were sorted randomly. 
Widgets reordered to have the following order:
=> Widgets reorder

orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py
Implements https://github.com/biolab/orange3-educational/issues/68
See also https://github.com/biolab/orange3-educational/pull/63
Points with the missing class variable as plotted as well as a gray points
=> PoliClass: Plot values without class label as grey points

MANIFEST.in, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/owpolynomialregression.py
Tests failed since PolynomialRegression imported Error from `OWWidget` instead of `OWBaseLearner`.
- Import fixed
- Updated MANIFEST.in to include license.
=> Import fix

orangecontrib/educational/widgets/ow1ka.py, orangecontrib/educational/widgets/owgooglesheets.py, orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/owpiecharts.py, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/owpolynomialregression.py, orangecontrib/educational/widgets/owrandomdata.py
Widgets lack keywords
Added keywords to widgets
=> Keywords for widgets

README.pypi, setup.cfg, setup.py
README for Github and README for PyPi should not be the same. PyPi doesn't format markdown and the description is often too long.
Have two separate READMEs - one for Github and one for PyPi (which is also shown in the add-on dialogue).
=> Provide separate README for PyPi

.travis.yml, orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/owpolynomialregression.py, orangecontrib/educational/widgets/tests/test_owgradientdescent.py, orangecontrib/educational/widgets/tests/test_owkmeans.py, orangecontrib/educational/widgets/tests/test_owpiecharts.py, orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owpolynomialregression.py, setup.py
After addon was updated there was a huge number of deprecations in Orange. 
With this PR I am removing those deprecated calls.
=> [FIX] Remove deprecated calls

orangecontrib/educational/widgets/utils/tests/test_kmeans.py, orangecontrib/educational/widgets/utils/tests/test_polynomialtransform.py, setup.py
- missing import
-test suites are deprecated
- replaced deprecated calls
This PR fixes all three issues
=> Fix educational package

.travis.yml
=> Travis add missing dependencies

doc/Makefile, doc/conf.py, setup.py
Documentation does not build on Windows
Changed the name where the documentation builds.
=> Updated documentation makefile

orangecontrib/educational/widgets/owgradientdescent.py, orangecontrib/educational/widgets/owpolynomialclassification.py, orangecontrib/educational/widgets/tests/test_owgradientdescent.py, orangecontrib/educational/widgets/tests/test_owpolynomialclassification.py
Variable.values are not lists but tuples, and must be passed as such.
=> Change argument for Variable.values from list to tuple

.travis.yml, orangecontrib/educational/widgets/highcharts/__init__.py, orangecontrib/educational/widgets/highcharts/tests/test_highcharts.py
=> Temporarily fix travis tests

orangecontrib/educational/widgets/owrandomdata.py
Widget breaks after the deprecation of left_side scrolling area.
This PR fixes resizing dependent on scrolling area. Merging this will cause that the widget will not have scrolling area anymore. Do we still want it? @janezd
=> Random data: Fix resize dependent on deprecated scrolling left_side

orangecontrib/educational/widgets/owrandomdata.py, orangecontrib/educational/widgets/tests/test_owrandomdata.py
Should fix #101.
@bughunter12345, I apologize this took so long. I couldn't (and still can't) reproduce the problem and, more importantly, this add-on was -- although we use it regularly -- somewhat neglected before becoming this year's summer project for me. :)
I added some code that should make parsing decimal numbers more robust. If you have time and you know how to and you're still interested, please check whether this fixes the problem. If not, @ajdapretnar will when she returns from vacation (right? :).
=> Random Data: Improve parsing of decimal values

doc/conf.py
Documentation build at read the docs is failing
Removing problematic and not required line of code
=> Documentation: fix failing rtd build

orangecontrib/educational/widgets/owkmeans.py, orangecontrib/educational/widgets/tests/test_owkmeans.py
Fixes #122.
Fix the dimensions of arrays with data for membership lines.
=> KMeans: Handle missing values

orangecontrib/educational/widgets/owrandomdata.py
=> Random Data: Rename variance to deviation

orangecontrib/educational/widgets/owrandomdata.py
Fixes #147.
Use a (similar) button as Create Class to make it more visible and easier to hit.
=> Random Data: Make x button easier to hit

.github/workflows/test.yml, orangecontrib/educational/widgets/owpolynomialregression.py
Windows-2016 is deprecated in GH Actions
Use latest windows, macOS and ubuntu
=> CI - Update test systems versions

.github/workflows/rebase.yaml
Automatic rebase is currently implemented at each repo separately
Use reusable workflow instead
=> Actions - automatic rebase reusable

orangecontrib/educational/widgets/owgradientdescent.py, tox.ini
Gradient descent not compatible with changes in orange-widget-base
Fix compatibility with hanging attribute type from array to list.
=> [FIX] Gradient descent - Fix compatibility with widget-base
